export const genreDisplayNames: Record<string, string> = {
  action: 'Action',
  adventure: 'Adventure',
  animeSeriesInternationalTvShows: 'Anime Series / International TV Shows',
  britishTvShowsDocuseriesInternationalTvShows:
    'British TV Shows / Docuseries / International TV Shows',
  children: 'Children',
  comedies: 'Comedies',
  comediesDramasInternationalMovies: 'Comedies / Dramas / International Movies',
  comediesInternationalMovies: 'Comedies / International Movies',
  comediesRomanticMovies: 'Comedies / Romantic Movies',
  crimeTvShowsDocuseries: 'Crime TV Shows / Docuseries',
  documentaries: 'Documentaries',
  documentariesInternationalMovies: 'Documentaries / International Movies',
  docuseries: 'Docuseries',
  dramas: 'Dramas',
  dramasInternationalMovies: 'Dramas / International Movies',
  dramasRomanticMovies: 'Dramas / Romantic Movies',
  familyMovies: 'Family Movies',
  fantasy: 'Fantasy',
  horrorMovies: 'Horror Movies',
  internationalMoviesThrillers: 'International Movies / Thrillers',
  internationalTvShowsRomanticTvShowsTvDramas:
    'International TV / Romantic Shows / TV Dramas',
  kidsTv: 'Kids TV',
  languageTvShows: 'Language TV Shows',
  musicals: 'Musicals',
  natureTv: 'Nature TV',
  realityTv: 'Reality TV',
  spirituality: 'Spirituality',
  tvAction: 'TV Action',
  tvComedies: 'TV Comedies',
  tvDramas: 'TV Dramas',
  talkShowsTvComedies: 'Talk Shows / TV Comedies',
  thrillers: 'Thrillers',
};
